name: starlife
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^4.0.1
  flutter_svg: ^1.1.6
  get_storage: ^2.0.3
  shared_preferences: ^2.0.16
  dio: ^4.0.6
  carousel_slider: ^4.2.1
  auto_size_text: ^3.0.0
  dart_date: ^1.1.1
  dropdown_button2: ^1.9.2
  convex_bottom_bar: ^3.2.0
  flutter_animated_dialog: ^2.0.1
  smooth_page_indicator: ^1.0.0+2
  flip_card: ^0.7.0
  fl_chart: ^0.60.0
  flutter_lints: ^2.0.1
  age_calculator: ^1.0.0
  jiffy: ^5.0.0
  webview_flutter_web: ^0.2.2+1
  image_picker: ^0.8.7
  video_player: ^2.6.0
  pdf: 3.10.0
  path_provider: 2.0.14
  open_file: 3.2.1
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icon/
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-Medium.ttf
    - assets/fonts/Poppins-SemiBold.ttf
    - assets/fonts/Poppins-Bold.ttf

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #       - asset: assets/fonts/Poppins-ExtraBold.ttf
  #         style: regular

  uses-material-design: true
